name: xcodebuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: brew
      run: brew install ragel
    - name: xcodebuild
      run: xcodebuild -target TwoTerm | xcpretty
